spring.application.name=docker-demo
spring.datasource.url=jdbc:postgresql://172.20.144.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=passgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Enable SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082
